### ISSUE TITLE
Rmi --all-stopped shortcut doesn't seem to be working

### ISSUE THREAD

**Issue by mchernyavskaya** [j-bennet/wharfee#154] opened 2017-07-19 19:52 UTC
`rmi --all-stopped` shortcut that is presented on the readme animation doesn't seem to be working. It doesn't show up in the autocompletion and when typed explicitly, gives an error.
```wharfee> rmi --all-stopped
Exception(u'Error parsing options: no such option: --all-stopped',)
```

<img width="534" alt="screen shot 2017-07-19 at 21 20 35" src="https://user-images.githubusercontent.com/538843/28386659-85b1d1f2-6ccc-11e7-877d-637dfe906d7c.png">

**Comment by j-bennet** [comment] 2017-07-19 20:24
There is `rm --all-stopped`, but no `rmi --all-stopped`. There's no such thing as "stopped images". You can do `rmi --all-dangling` though.

Closing as not a bug.

**Closed by j-bennet** 2017-07-19 20:24 UTC
